config/routes.rb
Rails.application.routes.draw do
  root "site_pages#index"
  get "password_reset/new"
  get "password_reset/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/songs", to: "songs#audio_download"
  post "songs/next", to: "songs#next"
  resources :account_activations, only: :edit
  resources :songs, only: :show
  resources :lyrics, only: :create
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: :index
  resources :lyrics, only: :create
  resources :comments
  resources :categories, only: [:show, :index]
  resources :artists, only: [:show, :index]
  resources :albums, only: [:show, :index]
  resources :favorites
  resources :favorite_songs
  namespace :admin do
    root to: "pages#home"
    resources :users
    resources :albums
    resources :categories
    resources :songs
    resources :lyrics
    resources :artists
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  has_many :favorite_songs, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :load_favorite, only: %i(show destroy)
  def create
    if logged_in?
      @favorite = Favorite.new name: params[:favorite][:name]
      @favorite.user = current_user
      @favorite.save
      @song = Song.find_by id: params[:favorite][:song_id]
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    @song = @favorite.songs.first
    @comment = Comment.new
    @comments = Comment.find_comment(@favorite.id, :Favorite).
      order_created_at.page(params[:page]).per 5
    if current_user
      @favorites = current_user.favorites
    end
  end

  def destroy
    @user = @favorite.user
    if @favorite.destroy
      flash[:success] = "Destroy favorite successful"
    else
      flash[:error] = "Can't delete Favorite"
    end
    redirect_to user_path(@user)
  end

  private
  def load_favorite
    @favorite = Favorite.find_by id: params[:id]
    return if @favorite
    flash[:danger] = "favorite not exist"
  end
end

app/views/favorites/_favorite.html.erb
<div class= "fl-<%= favorite.id %> fix-layouts-fl">
  <li class= "favorite_list">
    <div class="row">
      <div class="col-md-10">
        <%= link_to favorite_path(favorite) do %>
          <%= favorite.name %>
        <% end %>
      </div>
      <div class="col-md-2 pull-right">
        <% if favorite.songs.include?(@song) %>
          <%= link_to favorite_song_path(favorite.favorite_songs.find_by(song_id: @song.id)),
            method: :delete, remote: true do %>
            <div class="btn btn-danger">
              <%= t "favorite_lists.favorite.sub" %>
            </div>
          <% end %>
        <% else %>
          <%= link_to favorite_songs_path(favorite_id: favorite.id, 
            song_id: @song.id), method: :post, remote: true do %>
            <div class="btn btn-primary">
              <%= t "favorite_lists.favorite.add" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </li>
</div>

app/views/favorites/show.html.erb
<% if @song %>
  <div class="shoes-grid">
    <h3><%= t "views.favorite_lists.show.favorite_list" %>:&nbsp
      <%= @favorite.name %></h3>
    <div class="rating-section" data-fl-id= "<%= @favorite.id %>"
      data-type= "<%= @favorite.class.name %>">
    </div>
    <div class="album-audio-player">
      <%= render partial: "shared/audio_player", locals: {song: @song} %>
    </div>
    <div class="song-album">
      <ul>
        <%= render partial: "shared/song", collection: @favorite.songs %>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-2 pull-right">
        <h3>
          <span class="pull-left"><i class="fa fa-headphones fa-3px"></i></span>
            &nbsp<%= @favorite.view %>
        </h3>
      </div>
    </div>
    <div class="lyric-section">
      <% if @lyrics.present? %>
        <div class="lyric-header">
          <div class="row">
          <div class="col-md-4">
            <h4>
              <%= t "views.songs.show.lyric" %>:&nbsp
                <span class="song-name"><%= @song.name %></span>
            </h4>
          </div>
          <div class="col-md-4">
            <div class = "pull-right">
              <%= t "views.songs.show.contribute" %>:
              <span class="contribute">
                <%= @lyric.user.name %>
              </span>
            </div>
          </div>
          </div>
        </div>
        <div class= "lyric-content">
          <p><%= raw @lyric_item.content %></p>
        </div>
      <% else %>
        <%= t "views.songs.show.dont_have_lyric" %>
      <% end %>
      <div class= "lyric-footer">
        <a data-toggle="modal" data-target="#myModal1">
          <i><%= t "views.songs.show.contribute_lyric" %></i>
        </a>
      </div>
      <div class="modal fade" id="myModal1" role="dialog">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">
                <%= t "views.songs.show.contribute_lyric" %>
              </h4>
            </div>
            <div class="modal-body">
              <%= render "shared/form_lyric" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="comment-section">
      <div class="form-group well">
        <%= form_for @comment, remote: true do |f| %>
          <%= f.hidden_field :commentable_type, value: @favorite_list.class.name %>
          <%= f.hidden_field :commentable_id, value: @favorite_list.id %>
          <%= f.text_area :content, class: "form-control", 
            placeholder: t("views.songs.show.comment_here") %>
          <div class="submit-comment">
            <%= f.submit t("views.songs.show.submit"), 
              class: "btn btn-primary submit-comment-form" %>
          </div>
        <% end %>
      </div>
      <div class= "comment-content">
        <%= render partial: "shared/comment", collection: @comments %>
      </div>
      <p class="pagination">
        <%= link_to_next_page(@comments, "Next Page", :remote => true) %>
      </p>
    </div>
  </div>
<% else %>
  <div class="shoes-grid">
    <h3><%= t "views.favorite_lists.show.not_song" %></h3>
  </div>
  <div class="clearfix"> </div>
<% end %>
<div class="clearfix"> </div>    