config/routes.rb
Rails.application.routes.draw do
  root "site_pages#index"
  get "password_reset/new"
  get "password_reset/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/songs", to: "songs#audio_download"
  post "songs/next", to: "songs#next"
  resources :account_activations, only: :edit
  resources :songs, only: :show
  resources :lyrics, only: :create
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: :index
  resources :lyrics, only: :create
  resources :comments
  resources :categories, only: [:show, :index]
  resources :artists, only: [:show, :index]
  resources :albums, only: [:show, :index]
  resources :favorites
  resources :favorite_songs
  namespace :admin do
    root to: "pages#home"
    resources :users
    resources :albums
    resources :categories
    resources :songs
    resources :lyrics
    resources :artists
  end
end

app/views/shared/_audio_player.html.erb
<div class="audio-player" data-id= "<%= song.id %>">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag song.image %>
    </div>
    <div class="col-md-8">
      <div class="example1">
        <h3><%= song.name %></h3>
      </div>
    </div>
  </div>
  <%= audio_tag song.audio, autoplay: true, controls: true, class: "audio-song" %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_lyric.html.erb
<%= form_for :lyric, url: "/lyrics", remote: :true do |f| %>
  <%= f.hidden_field :song_id, value: @song.id %>
  <%= f.label :content, t("views.songs.show.content") %>
  <%= f.text_area :content, class: "form-control" %>
  <%= f.submit t("views.songs.show.submit"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_song.html.erb
<li class= "fix-border song-<%= song.id %>">
  <%= link_to songs_next_path(song_id: song.id), method: :post, remote: true do %>
  <div class="row">
    <div class="col-md-5">
      <%= song.name %>
    </div>
    <div class="col-md-6">
      <%= link_to songs_path(id: song.id), method: :post,
        class: "pull-right" do %>
        <span><i class="fa fa-download fa-2px"></i></span>
      <% end %>  
    </div>
  </div>
  <% end %>
</li>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>