config/routes.rb
Rails.application.routes.draw do
  root "site_pages#index"
  get "password_reset/new"
  get "password_reset/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/songs", to: "songs#audio_download"
  post "songs/next", to: "songs#next"
  resources :account_activations, only: :edit
  resources :songs, only: :show
  resources :lyrics, only: :create
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: :index
  resources :lyrics, only: :create
  resources :comments
  resources :categories, only: [:show, :index]
  resources :artists, only: [:show, :index]
  resources :albums, only: [:show, :index]
  resources :favorites
  resources :favorite_songs
  namespace :admin do
    root to: "pages#home"
    resources :users
    resources :albums
    resources :categories
    resources :songs
    resources :lyrics
    resources :artists
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  has_many :songs, dependent: :destroy

  scope :load_all, ->{select(:id, :title, :describe).order :title}
  scope :order_by_name, ->{order created_at: :desc}
  scope :search_by_name, -> search{
    select(:id, :title).where "title LIKE ?", "%#{search}%"
  }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :load_category, only: %i(update, edit, destroy)
  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admin_categories_path
      flash[:success] = t("admin.flash.successful", obj: "Category", action: "create")
    else
      flash[:error] = t("admin.flash.failed", obj: "Category", action: "create")
      render :new
    end
  end

  def index
    @categories = Category.page(params[:page]).per(10)
    return unless params[:search]
    @categories = Category.search(params[:search]).desc_at_create.page(params[:page]).per Settings.show_limit.per_page
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t("admin.flash.successful", obj: "Category", action: "update")
    else
      flash[:error] = t("admin.flash.failed", obj: "Category", action: "update")
    end
    redirect_to admin_categories_path
  end

  def destroy
    if @category.destroy
      flash[:success] = t("admin.flash.successful", obj: "Category", action: "destroy")
    else
      flash[:error] = t("admin.flash.failed", obj: "Category", action: "destroy")
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit :title
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:error] = t("admin.flash.successful", obj: "Category", id: params[:id])
    redirect_to admin_categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: :show
  def show
    @songs = @category.songs.page(params[:page]).per 10
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @categories = Category.all
    return unless params[:search]
    @categories = Category.order_by_name
                          .search_by_name(params[:search])
                          .page(params[:page]).per Settings.show_limit.per_page
  end
  private
  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = "Category not found"
    redirect_to root_path
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.title %></td>
  <td><%= category.created_at %></td>
  <td>
    <%= link_to edit_admin_category_path(category) do %>
      <span><i class="fa fa-edit fa-1px"></i></span>
    <% end %>
  </td>
  <td>
    <%= link_to admin_categories_path(category), method: :delete, data: {confirm: "Are you sure? You will delete all songs belongs to this category!!danger"} do %>
      <span><i class="fa fa-times fa-1px"></i></span>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.label :title, t("admin.categories.title") %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :describe, t("admin.albums.describe") %>
      <%= f.text_field :describe, class: "form-control"%>
    </div>
    <div class="field">
      <%= f.submit :Submit, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, t("admin.categories.edit_title")) %>
<% provide(:button_text, t("admin.albums.edit_sumbmit")) %>
<h1><%= t "admin.categories.edit_submit" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h3 class="sub-header"><%= t "admin.categories.category_list" %></h3>
    <%= form_tag(admin_categories_path, method: :get) do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "search", name: nil %>
    <% end %><br/>
    <%= link_to new_admin_category_path do %><%= t "admin.categories.new_category" %>
      <span><i class="fa fa-plus fa-2px"></i></span>
    <% end %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th><%= t "admin.categories.title" %></th>
            <th><%= t "admin.albums.created_at" %></th>
            <th><%= t "admin.albums.edit" %></th>
            <th><%= t "admin.albums.delete" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "category", collection: @categories %>
        </tbody>
      </table>
      <%= paginate @categories %>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, t("admin.categories.new_category")) %>
<% provide(:button_text, t("admin.albums.create")) %>
<h1>New Category</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>