config/routes.rb
Rails.application.routes.draw do
  root "site_pages#index"
  get "password_reset/new"
  get "password_reset/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/songs", to: "songs#audio_download"
  post "songs/next", to: "songs#next"
  resources :account_activations, only: :edit
  resources :songs, only: :show
  resources :lyrics, only: :create
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users, except: :index
  resources :lyrics, only: :create
  resources :comments
  resources :categories, only: [:show, :index]
  resources :artists, only: [:show, :index]
  resources :albums, only: [:show, :index]
  resources :favorites
  resources :favorite_songs
  namespace :admin do
    root to: "pages#home"
    resources :users
    resources :albums
    resources :categories
    resources :songs
    resources :lyrics
    resources :artists
  end
end

app/views/admin/layouts/_header.html.erb
  <div class="navbar-header">
    <a class="navbar-brand" href="<%= admin_root_path %>"><%= t "admin.layouts.title" %></a>
  </div>
  <form class="navbar-form navbar-right">
    <% if logged_in? %>
	    <li class="nav-item">
	      <%= link_to (t "layouts.logout"), logout_path, method: :delete, class: "nav-link" %>
	    </li>
	  <% else %>
	    <li class="nav-item">
	      <%= link_to (t "layouts.login"), "/", class: "nav-link" %>
	    </li>
	    <li class="nav-item">
	      <%= link_to (t "layouts.signup"), "/", class: "nav-link" %>
	    </li>
	  <% end %>
  </form>
</nav>

app/views/admin/layouts/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav">
      <ul class="nav" id="side-menu">
        <li>
        </li>
        <li>
          <%= link_to "Users", admin_users_path %>
        </li>
        <li>
          <%= link_to "Categories", admin_categories_path %>
        </li>
        <li>
          <%= link_to "Songs", admin_songs_path %>
        </li>
        <li>
          <%= link_to "Albums", admin_albums_path %>
        </li>
        <li>
          <%= link_to "Artists", admin_artists_path %>
        </li>
        <li>
          <%= link_to "Lyrics", admin_lyrics_path %>
        </li>
      </ul>
  </div>
</div>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div id="wrapper">
      <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <%= render "admin/layouts/header" %>
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2 sidebar fix-sidebar">
              <%= render "admin/layouts/sidebar" %>
            </div>
            <div class="col-md-10 sidebar fix-sidebar">
              <div class="graphs">
                <% flash.each do |message_type, message| %>
                  <div class="alert alert-<%= message_type %>">
                      <%= message %>
                  </div>
                <% end %>
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </body>
</html>